<a href="https://colab.research.google.com/github/freddy-7/TI2001B-2023/blob/main/1_Extracci%C3%B3n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#GOOGLE COLAB
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

CARGA DE ARCHIVO XLSX

In [5]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx')
df

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [6]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No. CLIENTE        164 non-null    object
 1   NOMBRE             164 non-null    str
 2   FACTURA            164 non-null    str
 3   FECHA_FACTURA      164 non-null    datetime64[us]
 4   FECHA_VENCIMIENTO  164 non-null    datetime64[us]
 5   MONTO ADEUDADO     164 non-null    float64
dtypes: datetime64[us](2), float64(1), object(1), str(2)
memory usage: 12.2+ KB

ITERACIÓN

**Iterar columnas directamente del dataframe**

In [11]:
# Iterar sobre la columna 'nombre'
for nombre in df['NOMBRE']:
    print(nombre)

DONGA HWASUNG MEXICO
DONGA HWASUNG MEXICO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
INDUSTRIAS LANCERMEX
HELVEX
AUTOLIV STEERING WHEELS MEXICO
AUTOLIV STEERING WHEELS MEXICO
BUSSMANN
CLAVOS NACIONALES C.N
CLAVOS NACIONALES C.N
RICHALUM
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
INDUSTRIAS LANCERMEX
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
AUTOLIV STEERING WHEELS MEXICO
PQUISEM
SIEGFRIED RHEIN
SIEGFRIED RHEIN
MOLINERA DE MEXICO
Q SEALS DE MEXICO
Q SEALS DE MEXICO
SIEGFRIED RHEIN
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
DEACERO
TE.MEX AUTOMOTIVE
DIECASTING CELAYA
CLAVOS NACIONALES C.N
CEREALES Y PASTAS
PLENCO DE MEXICO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
DEACERO
GLASSER
NESTLE MEXICO
AIRBUS HELICOPTERS MEXICO QUERETARO
AIRBUS HELICOPTERS MEXICO QUERETARO
SIKA MEXICANA
COVEMEX
HOT MELT SISTEMAS Y SERVICIOS SANCHEZ
EDGAR GARCIA HERNANDEZ
BUSSMANN
SIKA MEXICANA
DWK LIFE SCIENCES
SIEGFRIED RHEIN
DONGA HWASUNG MEXICO
BACHOCO
SIEGFRIED RHEIN
PREFORMADOS DE MEXICO
CEREALES Y PASTAS
EMPACADORA CELAYA
FIDEICOMISO F/1596
DWK LIFE SCIENCES
DONGA HWASUNG MEXICO
DEACERO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
BETA PROCESOS
DEACERO
BEDACOM
NIHON PLAST MEXICANA
GLASSER
CEREALES Y PASTAS
FRESCOS DON GU
DEACERO
KERN LIEBERS MEXICO
PQUISEM
EDGAR GARCIA HERNANDEZ
KERN LIEBERS MEXICO
DEACERO
CONTROLADORA MABE
ITW POLY MEX
ANA BARBARA CRUZ PALACIOS
ARMANDO VIDAURRETA PEÑA
CEREALES Y PASTAS
DISTRIBUCIONES Y REPRESENTACIONES CALORA
OERLIKON BALZERS COATING MEXICO
APEX TOOL GROUP MANUFACTURING MEXICO
SIEGFRIED RHEIN
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
HOBBY ELECTRONICA
DAVID LICEA PANDURO
CEREALES Y PASTAS
INDUSTRIAS TOLJY
SANKO GOSEI MEXICO
VINILOS
CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS INDUSTRIALES
EDGAR GARCIA HERNANDEZ
KERN LIEBERS MEXICO
RL ELECTRICO
BETA PROCESOS
ITW POLY MEX
PERFORMANCE COATING
ADVANEX DE MEXICO
J. FRANCISCO FERRUZCA HERNANDEZ
DEACERO
MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACCION DEL CENTRO
PRODUCTOS PENNSYLVANIA
SIEGFRIED RHEIN
MEXICANA DE INGENIERIA Y MAQUINARIA
APEX TOOL GROUP MANUFACTURING MEXICO
PRODUCTOS PENNSYLVANIA
PÚBLICO EN GENERAL
RAUL SERVIN AGUILLON
BLANCA ROCIO GARCIA MORALES
VINILOS
ALIMENTOS GOURMET DEL BAJIO
DEACERO
JORGE HERBERT PEREZ
CAPTIVE SPORT
CEREALES Y PASTAS
ELASTOMEROS DE QUERETARO
ABASTECEDORA GOURMET
LBQ FOUNDRY
FRESCOPACK
MARI CARMEN ALONZO MORA
HOSPITAL SAN JOSE DE CELAYA
SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUSTRIAL
CARLOS ALBERTO HERNANDEZ MIRANDA
DEX STAR
VINILOS
EMZ HANAUER DE MEXICO
OSANIA CLEANING & SANITIZING
KERN LIEBERS MEXICO
MECAPRIM SERVICIOS INDUSTRIALES
JAKBA-SEE
MULTI EQUIPOS AUTOMOTRICES VIZU
GRUPO ROCE INDUSTRIAL Y COMERCIAL
JOSE ALEJANDRO DIAZ NIETO
GRUPO ROCE INDUSTRIAL Y COMERCIAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
TERMOFORMADOS
MARATHON SYSTEMS CONTROL
FRANCISCO JAVIER MEDINA SANCHEZ
GABRIELA GARCIA SANCHEZ
MECAPRIM SERVICIOS INDUSTRIALES
JOSE ALEJANDRO DIAZ NIETO
JV AGRO
UCH COMERCIAL
POLIETILENOS Y PRODUCTOS DE QUERETARO
PÚBLICO EN GENERAL
DISTRIBUIDORA LIVERPOOL
TRATAMIENTOS TERMICOS DE QUERETARO
PÚBLICO EN GENERAL
CAPTIVE SPORT
HEVACSA TERMOENCOGIBLES
ELECTRO FERRETERA REAL
SCIMPLA
ANA KARLA ROSALES VAZQUEZ
LBQ FOUNDRY
MANUFACTURERA SLY
PÚBLICO EN GENERAL
J H MILLS
PÚBLICO EN GENERAL
BURBUPAC DE QUERETARO
AT Y V DESARROLLOS Y MANUFACTURAS
PÚBLICO EN GENERAL
OLMO RACKS & DUNNAGE
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
FISHERS QUERETARO

***USANDO NUMPY***

**Iterar columnas tipo STRING**

In [31]:
# Iterar sobre una columna tipo string: 'NOMBRE' con Numpy
nombres = df['NOMBRE'].to_numpy() #Primero convertimos la columna en un array

# Iterar sobre el array
for nombre in np.nditer(nombres, flags=['refs_ok']): #Usamos flags=['refs_ok'] si la columna contiene strings (objetos) en lugar de números
    print(nombre.item())  # item() lo convierte a string nativo de Python

DONGA HWASUNG MEXICO
DONGA HWASUNG MEXICO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
INDUSTRIAS LANCERMEX
HELVEX
AUTOLIV STEERING WHEELS MEXICO
AUTOLIV STEERING WHEELS MEXICO
BUSSMANN
CLAVOS NACIONALES C.N
CLAVOS NACIONALES C.N
RICHALUM
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
INDUSTRIAS LANCERMEX
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
AUTOLIV STEERING WHEELS MEXICO
PQUISEM
SIEGFRIED RHEIN
SIEGFRIED RHEIN
MOLINERA DE MEXICO
Q SEALS DE MEXICO
Q SEALS DE MEXICO
SIEGFRIED RHEIN
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
DEACERO
TE.MEX AUTOMOTIVE
DIECASTING CELAYA
CLAVOS NACIONALES C.N
CEREALES Y PASTAS
PLENCO DE MEXICO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
DEACERO
GLASSER
NESTLE MEXICO
AIRBUS HELICOPTERS MEXICO QUERETARO
AIRBUS HELICOPTERS MEXICO QUERETARO
SIKA MEXICANA
COVEMEX
HOT MELT SISTEMAS Y SERVICIOS SANCHEZ
EDGAR GARCIA HERNANDEZ
BUSSMANN
SIKA MEXICANA
DWK LIFE SCIENCES
SIEGFRIED RHEIN
DONGA HWASUNG MEXICO
BACHOCO
SIEGFRIED RHEIN
PREFORMADOS DE MEXICO
CEREALES Y PASTAS
EMPACADORA CELAYA
FIDEICOMISO F/1596
DWK LIFE SCIENCES
DONGA HWASUNG MEXICO
DEACERO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
BETA PROCESOS
DEACERO
BEDACOM
NIHON PLAST MEXICANA
GLASSER
CEREALES Y PASTAS
FRESCOS DON GU
DEACERO
KERN LIEBERS MEXICO
PQUISEM
EDGAR GARCIA HERNANDEZ
KERN LIEBERS MEXICO
DEACERO
CONTROLADORA MABE
ITW POLY MEX
ANA BARBARA CRUZ PALACIOS
ARMANDO VIDAURRETA PEÑA
CEREALES Y PASTAS
DISTRIBUCIONES Y REPRESENTACIONES CALORA
OERLIKON BALZERS COATING MEXICO
APEX TOOL GROUP MANUFACTURING MEXICO
SIEGFRIED RHEIN
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
HOBBY ELECTRONICA
DAVID LICEA PANDURO
CEREALES Y PASTAS
INDUSTRIAS TOLJY
SANKO GOSEI MEXICO
VINILOS
CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS INDUSTRIALES
EDGAR GARCIA HERNANDEZ
KERN LIEBERS MEXICO
RL ELECTRICO
BETA PROCESOS
ITW POLY MEX
PERFORMANCE COATING
ADVANEX DE MEXICO
J. FRANCISCO FERRUZCA HERNANDEZ
DEACERO
MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACCION DEL CENTRO
PRODUCTOS PENNSYLVANIA
SIEGFRIED RHEIN
MEXICANA DE INGENIERIA Y MAQUINARIA
APEX TOOL GROUP MANUFACTURING MEXICO
PRODUCTOS PENNSYLVANIA
PÚBLICO EN GENERAL
RAUL SERVIN AGUILLON
BLANCA ROCIO GARCIA MORALES
VINILOS
ALIMENTOS GOURMET DEL BAJIO
DEACERO
JORGE HERBERT PEREZ
CAPTIVE SPORT
CEREALES Y PASTAS
ELASTOMEROS DE QUERETARO
ABASTECEDORA GOURMET
LBQ FOUNDRY
FRESCOPACK
MARI CARMEN ALONZO MORA
HOSPITAL SAN JOSE DE CELAYA
SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUSTRIAL
CARLOS ALBERTO HERNANDEZ MIRANDA
DEX STAR
VINILOS
EMZ HANAUER DE MEXICO
OSANIA CLEANING & SANITIZING
KERN LIEBERS MEXICO
MECAPRIM SERVICIOS INDUSTRIALES
JAKBA-SEE
MULTI EQUIPOS AUTOMOTRICES VIZU
GRUPO ROCE INDUSTRIAL Y COMERCIAL
JOSE ALEJANDRO DIAZ NIETO
GRUPO ROCE INDUSTRIAL Y COMERCIAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
TERMOFORMADOS
MARATHON SYSTEMS CONTROL
FRANCISCO JAVIER MEDINA SANCHEZ
GABRIELA GARCIA SANCHEZ
MECAPRIM SERVICIOS INDUSTRIALES
JOSE ALEJANDRO DIAZ NIETO
JV AGRO
UCH COMERCIAL
POLIETILENOS Y PRODUCTOS DE QUERETARO
PÚBLICO EN GENERAL
DISTRIBUIDORA LIVERPOOL
TRATAMIENTOS TERMICOS DE QUERETARO
PÚBLICO EN GENERAL
CAPTIVE SPORT
HEVACSA TERMOENCOGIBLES
ELECTRO FERRETERA REAL
SCIMPLA
ANA KARLA ROSALES VAZQUEZ
LBQ FOUNDRY
MANUFACTURERA SLY
PÚBLICO EN GENERAL
J H MILLS
PÚBLICO EN GENERAL
BURBUPAC DE QUERETARO
AT Y V DESARROLLOS Y MANUFACTURAS
PÚBLICO EN GENERAL
OLMO RACKS & DUNNAGE
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
FISHERS QUERETARO

**Iterar columnas tipo NUMÉRICO**

In [13]:
# Iterar sobre una columna tipo numérico: 'MONTO ADEUDADO' con Numpy
monto_adeudado = df['MONTO ADEUDADO'].to_numpy() # Convertir la columna 'MONTO ADEUDADO' a array de NumPy

# Iterar sobre el array
for monto_adeudado in np.nditer(monto_adeudado):
    print(monto_adeudado)  # monto_adeudado es directamente un número (int o float)

97485.94
97485.94
64916.21
52715.74
50639.8
49416.0
49416.0
48882.12
45216.34
45216.34
42880.05
37588.59
35143.82
34493.76
32886.0
30880.31
30276.0
30276.0
29642.92
29562.6
29197.72
26795.86
25670.22
23872.8
22956.4
21440.02
21179.28
20610.88
19301.82
17975.65
17579.52
17400.0
17271.23
16240.0
16240.0
15878.08
15843.28
13747.65
13086.19
12474.0
12057.04
11067.54
11019.94
10759.0
10565.28
10467.83
10440.0
10226.56
10092.0
9540.77
9472.53
9396.0
9032.92
8653.6
8653.6
8463.31
8266.67
8243.54
8190.46
7882.4
7714.0
7081.8
6840.66
6820.8
6612.0
6496.0
6438.19
6351.0
6264.0
6264.0
5967.85
5827.84
5800.0
5660.8
5502.81
5474.5
5443.47
5414.3
5373.1
5313.73
5253.51
4721.2
4640.0
4541.4
4512.28
4292.0
4173.62
4158.6
4080.3
4022.13
3971.93
3830.0
3480.0
3451.0
3399.38
3375.14
3368.64
3248.58
3183.04
3166.38
2756.16
2694.95
2526.48
2334.5
2256.14
2094.96
2088.0
2000.0
1949.38
1925.6
1827.0
1740.79
1740.0
1682.0
1682.0
1647.2
1608.15
1479.0
1401.57
1390.72
1264.4
1229.95
1204.08
1179.95
1169.28
1095.85
1068.28
1015.0
1000.0
1000.0
1000.0
815.0
799.24
765.6
763.04
754.0
742.4
730.01
704.41
702.96
658.6
591.6
568.4
555.19
500.0
500.0
487.2
487.2
420.0
406.0
366.04
313.5
300.0
262.74
200.0
191.04
139.2
130.0
87.35
56.0
45.0
40.0
24.01
19.94

**Iterar Filas**

In [25]:
# Iterar sobre cada fila del dataframe
for index, row in df.iterrows():
    print(f"Fila {index}:")
    print(f"NOMBRE: {row['NOMBRE']}")
    print(f"FECHA DE VENCIMIENTO: {row['FECHA_VENCIMIENTO']}")
    print("-----")

Fila 0:
NOMBRE: DONGA HWASUNG MEXICO
FECHA DE VENCIMIENTO: 2023-03-26 00:00:00
-----
Fila 1:
NOMBRE: DONGA HWASUNG MEXICO
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 2:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 3:
NOMBRE: INDUSTRIAS LANCERMEX
FECHA DE VENCIMIENTO: 2023-03-25 00:00:00
-----
Fila 4:
NOMBRE: HELVEX
FECHA DE VENCIMIENTO: 2023-04-03 00:00:00
-----
Fila 5:
NOMBRE: AUTOLIV STEERING WHEELS MEXICO
FECHA DE VENCIMIENTO: 2023-03-25 00:00:00
-----
Fila 6:
NOMBRE: AUTOLIV STEERING WHEELS MEXICO
FECHA DE VENCIMIENTO: 2023-05-07 00:00:00
-----
Fila 7:
NOMBRE: BUSSMANN
FECHA DE VENCIMIENTO: 2023-02-04 00:00:00
-----
Fila 8:
NOMBRE: CLAVOS NACIONALES C.N
FECHA DE VENCIMIENTO: 2023-05-12 00:00:00
-----
Fila 9:
NOMBRE: CLAVOS NACIONALES C.N
FECHA DE VENCIMIENTO: 2023-05-13 00:00:00
-----
Fila 10:
NOMBRE: RICHALUM
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 11:
NOMBRE: TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-03-12 00:00:00
-----
Fila 12:
NOMBRE: INDUSTRIAS LANCERMEX
FECHA DE VENCIMIENTO: 2023-03-11 00:00:00
-----
Fila 13:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-03-19 00:00:00
-----
Fila 14:
NOMBRE: AUTOLIV STEERING WHEELS MEXICO
FECHA DE VENCIMIENTO: 2023-03-06 00:00:00
-----
Fila 15:
NOMBRE: PQUISEM
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 16:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-02-27 00:00:00
-----
Fila 17:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-03-04 00:00:00
-----
Fila 18:
NOMBRE: MOLINERA DE MEXICO
FECHA DE VENCIMIENTO: 2023-03-29 00:00:00
-----
Fila 19:
NOMBRE: Q SEALS DE MEXICO
FECHA DE VENCIMIENTO: 2023-05-12 00:00:00
-----
Fila 20:
NOMBRE: Q SEALS DE MEXICO
FECHA DE VENCIMIENTO: 2023-04-02 00:00:00
-----
Fila 21:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-04-10 00:00:00
-----
Fila 22:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 23:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2023-04-16 00:00:00
-----
Fila 24:
NOMBRE: TE.MEX AUTOMOTIVE
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 25:
NOMBRE: DIECASTING CELAYA
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 26:
NOMBRE: CLAVOS NACIONALES C.N
FECHA DE VENCIMIENTO: 2023-03-26 00:00:00
-----
Fila 27:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 28:
NOMBRE: PLENCO DE MEXICO
FECHA DE VENCIMIENTO: 2023-03-18 00:00:00
-----
Fila 29:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 30:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2023-01-22 00:00:00
-----
Fila 31:
NOMBRE: GLASSER
FECHA DE VENCIMIENTO: 2023-02-03 00:00:00
-----
Fila 32:
NOMBRE: NESTLE MEXICO
FECHA DE VENCIMIENTO: 2023-03-01 00:00:00
-----
Fila 33:
NOMBRE: AIRBUS HELICOPTERS MEXICO QUERETARO
FECHA DE VENCIMIENTO: 2023-04-04 00:00:00
-----
Fila 34:
NOMBRE: AIRBUS HELICOPTERS MEXICO QUERETARO
FECHA DE VENCIMIENTO: 2023-04-04 00:00:00
-----
Fila 35:
NOMBRE: SIKA MEXICANA
FECHA DE VENCIMIENTO: 2023-04-07 00:00:00
-----
Fila 36:
NOMBRE: COVEMEX
FECHA DE VENCIMIENTO: 2023-03-29 00:00:00
-----
Fila 37:
NOMBRE: HOT MELT SISTEMAS Y SERVICIOS SANCHEZ
FECHA DE VENCIMIENTO: 2023-03-03 00:00:00
-----
Fila 38:
NOMBRE: EDGAR GARCIA HERNANDEZ
FECHA DE VENCIMIENTO: 2023-03-28 00:00:00
-----
Fila 39:
NOMBRE: BUSSMANN
FECHA DE VENCIMIENTO: 2022-11-15 00:00:00
-----
Fila 40:
NOMBRE: SIKA MEXICANA
FECHA DE VENCIMIENTO: 2023-04-06 00:00:00
-----
Fila 41:
NOMBRE: DWK LIFE SCIENCES
FECHA DE VENCIMIENTO: 2023-03-01 00:00:00
-----
Fila 42:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-03-25 00:00:00
-----
Fila 43:
NOMBRE: DONGA HWASUNG MEXICO
FECHA DE VENCIMIENTO: 2023-04-07 00:00:00
-----
Fila 44:
NOMBRE: BACHOCO
FECHA DE VENCIMIENTO: 2022-01-22 00:00:00
-----
Fila 45:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-04-10 00:00:00
-----
Fila 46:
NOMBRE: PREFORMADOS DE MEXICO
FECHA DE VENCIMIENTO: 2023-03-31 00:00:00
-----
Fila 47:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 48:
NOMBRE: EMPACADORA CELAYA
FECHA DE VENCIMIENTO: 2022-08-13 00:00:00
-----
Fila 49:
NOMBRE: FIDEICOMISO F/1596
FECHA DE VENCIMIENTO: 2023-03-09 00:00:00
-----
Fila 50:
NOMBRE: DWK LIFE SCIENCES
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 51:
NOMBRE: DONGA HWASUNG MEXICO
FECHA DE VENCIMIENTO: 2023-03-29 00:00:00
-----
Fila 52:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2022-10-09 00:00:00
-----
Fila 53:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-01-21 00:00:00
-----
Fila 54:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-03-04 00:00:00
-----
Fila 55:
NOMBRE: TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-04-07 00:00:00
-----
Fila 56:
NOMBRE: BETA PROCESOS
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 57:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2022-11-05 00:00:00
-----
Fila 58:
NOMBRE: BEDACOM
FECHA DE VENCIMIENTO: 2021-12-09 00:00:00
-----
Fila 59:
NOMBRE: NIHON PLAST MEXICANA
FECHA DE VENCIMIENTO: 2023-03-17 00:00:00
-----
Fila 60:
NOMBRE: GLASSER
FECHA DE VENCIMIENTO: 2023-02-03 00:00:00
-----
Fila 61:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 62:
NOMBRE: FRESCOS DON GU
FECHA DE VENCIMIENTO: 2023-03-23 00:00:00
-----
Fila 63:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2023-04-16 00:00:00
-----
Fila 64:
NOMBRE: KERN LIEBERS MEXICO
FECHA DE VENCIMIENTO: 2023-02-14 00:00:00
-----
Fila 65:
NOMBRE: PQUISEM
FECHA DE VENCIMIENTO: 2023-03-21 00:00:00
-----
Fila 66:
NOMBRE: EDGAR GARCIA HERNANDEZ
FECHA DE VENCIMIENTO: 2023-03-11 00:00:00
-----
Fila 67:
NOMBRE: KERN LIEBERS MEXICO
FECHA DE VENCIMIENTO: 2023-03-26 00:00:00
-----
Fila 68:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2023-04-29 00:00:00
-----
Fila 69:
NOMBRE: CONTROLADORA MABE
FECHA DE VENCIMIENTO: 2022-10-26 00:00:00
-----
Fila 70:
NOMBRE: ITW POLY MEX
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 71:
NOMBRE: ANA BARBARA CRUZ PALACIOS
FECHA DE VENCIMIENTO: 2023-03-31 00:00:00
-----
Fila 72:
NOMBRE: ARMANDO VIDAURRETA PEÑA
FECHA DE VENCIMIENTO: 2022-12-14 00:00:00
-----
Fila 73:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 74:
NOMBRE: DISTRIBUCIONES Y REPRESENTACIONES CALORA
FECHA DE VENCIMIENTO: 2023-04-22 00:00:00
-----
Fila 75:
NOMBRE: OERLIKON BALZERS COATING MEXICO
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 76:
NOMBRE: APEX TOOL GROUP MANUFACTURING MEXICO
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 77:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-04-17 00:00:00
-----
Fila 78:
NOMBRE: TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-03-18 00:00:00
-----
Fila 79:
NOMBRE: HOBBY ELECTRONICA
FECHA DE VENCIMIENTO: 2023-04-05 00:00:00
-----
Fila 80:
NOMBRE: DAVID LICEA PANDURO
FECHA DE VENCIMIENTO: 2023-03-09 00:00:00
-----
Fila 81:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 82:
NOMBRE: INDUSTRIAS TOLJY
FECHA DE VENCIMIENTO: 2023-03-03 00:00:00
-----
Fila 83:
NOMBRE: SANKO GOSEI MEXICO
FECHA DE VENCIMIENTO: 2023-02-17 00:00:00
-----
Fila 84:
NOMBRE: VINILOS
FECHA DE VENCIMIENTO: 2023-03-31 00:00:00
-----
Fila 85:
NOMBRE: CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 86:
NOMBRE: EDGAR GARCIA HERNANDEZ
FECHA DE VENCIMIENTO: 2023-02-17 00:00:00
-----
Fila 87:
NOMBRE: KERN LIEBERS MEXICO
FECHA DE VENCIMIENTO: 2023-03-19 00:00:00
-----
Fila 88:
NOMBRE: RL ELECTRICO
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 89:
NOMBRE: BETA PROCESOS
FECHA DE VENCIMIENTO: 2023-03-30 00:00:00
-----
Fila 90:
NOMBRE: ITW POLY MEX
FECHA DE VENCIMIENTO: 2023-04-12 00:00:00
-----
Fila 91:
NOMBRE: PERFORMANCE COATING
FECHA DE VENCIMIENTO: 2021-01-18 00:00:00
-----
Fila 92:
NOMBRE: ADVANEX DE MEXICO
FECHA DE VENCIMIENTO: 2022-05-06 00:00:00
-----
Fila 93:
NOMBRE: J. FRANCISCO FERRUZCA HERNANDEZ
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 94:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2022-12-10 00:00:00
-----
Fila 95:
NOMBRE: MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACCION DEL CENTRO
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 96:
NOMBRE: PRODUCTOS PENNSYLVANIA
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 97:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-02-20 00:00:00
-----
Fila 98:
NOMBRE: MEXICANA DE INGENIERIA Y MAQUINARIA
FECHA DE VENCIMIENTO: 2023-03-04 00:00:00
-----
Fila 99:
NOMBRE: APEX TOOL GROUP MANUFACTURING MEXICO
FECHA DE VENCIMIENTO: 2023-03-26 00:00:00
-----
Fila 100:
NOMBRE: PRODUCTOS PENNSYLVANIA
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 101:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 102:
NOMBRE: RAUL SERVIN AGUILLON
FECHA DE VENCIMIENTO: 2023-03-15 00:00:00
-----
Fila 103:
NOMBRE: BLANCA ROCIO GARCIA MORALES
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 104:
NOMBRE: VINILOS
FECHA DE VENCIMIENTO: 2023-03-31 00:00:00
-----
Fila 105:
NOMBRE: ALIMENTOS GOURMET DEL BAJIO
FECHA DE VENCIMIENTO: 2021-08-23 00:00:00
-----
Fila 106:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2022-11-05 00:00:00
-----
Fila 107:
NOMBRE: JORGE HERBERT PEREZ
FECHA DE VENCIMIENTO: 2021-08-23 00:00:00
-----
Fila 108:
NOMBRE: CAPTIVE SPORT
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 109:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 110:
NOMBRE: ELASTOMEROS DE QUERETARO
FECHA DE VENCIMIENTO: 2023-04-12 00:00:00
-----
Fila 111:
NOMBRE: ABASTECEDORA GOURMET
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 112:
NOMBRE: LBQ FOUNDRY
FECHA DE VENCIMIENTO: 2023-03-09 00:00:00
-----
Fila 113:
NOMBRE: FRESCOPACK
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 114:
NOMBRE: MARI CARMEN ALONZO MORA
FECHA DE VENCIMIENTO: 2023-02-27 00:00:00
-----
Fila 115:
NOMBRE: HOSPITAL SAN JOSE DE CELAYA
FECHA DE VENCIMIENTO: 2021-08-28 00:00:00
-----
Fila 116:
NOMBRE: SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUSTRIAL
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 117:
NOMBRE: CARLOS ALBERTO HERNANDEZ MIRANDA
FECHA DE VENCIMIENTO: 2023-01-16 00:00:00
-----
Fila 118:
NOMBRE: DEX STAR
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 119:
NOMBRE: VINILOS
FECHA DE VENCIMIENTO: 2023-03-31 00:00:00
-----
Fila 120:
NOMBRE: EMZ HANAUER DE MEXICO
FECHA DE VENCIMIENTO: 2023-02-08 00:00:00
-----
Fila 121:
NOMBRE: OSANIA CLEANING & SANITIZING
FECHA DE VENCIMIENTO: 2022-11-05 00:00:00
-----
Fila 122:
NOMBRE: KERN LIEBERS MEXICO
FECHA DE VENCIMIENTO: 2023-02-14 00:00:00
-----
Fila 123:
NOMBRE: MECAPRIM SERVICIOS INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-03-15 00:00:00
-----
Fila 124:
NOMBRE: JAKBA-SEE
FECHA DE VENCIMIENTO: 2023-03-16 00:00:00
-----
Fila 125:
NOMBRE: MULTI EQUIPOS AUTOMOTRICES VIZU
FECHA DE VENCIMIENTO: 2023-01-31 00:00:00
-----
Fila 126:
NOMBRE: GRUPO ROCE INDUSTRIAL Y COMERCIAL
FECHA DE VENCIMIENTO: 2023-01-31 00:00:00
-----
Fila 127:
NOMBRE: JOSE ALEJANDRO DIAZ NIETO
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 128:
NOMBRE: GRUPO ROCE INDUSTRIAL Y COMERCIAL
FECHA DE VENCIMIENTO: 2023-02-02 00:00:00
-----
Fila 129:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-10-05 00:00:00
-----
Fila 130:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2022-01-27 00:00:00
-----
Fila 131:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-08-16 00:00:00
-----
Fila 132:
NOMBRE: TERMOFORMADOS
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 133:
NOMBRE: MARATHON SYSTEMS CONTROL
FECHA DE VENCIMIENTO: 2023-02-11 00:00:00
-----
Fila 134:
NOMBRE: FRANCISCO JAVIER MEDINA SANCHEZ
FECHA DE VENCIMIENTO: 2022-10-27 00:00:00
-----
Fila 135:
NOMBRE: GABRIELA GARCIA SANCHEZ
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 136:
NOMBRE: MECAPRIM SERVICIOS INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-03-15 00:00:00
-----
Fila 137:
NOMBRE: JOSE ALEJANDRO DIAZ NIETO
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 138:
NOMBRE: JV AGRO
FECHA DE VENCIMIENTO: 2023-03-15 00:00:00
-----
Fila 139:
NOMBRE: UCH COMERCIAL
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 140:
NOMBRE: POLIETILENOS Y PRODUCTOS DE QUERETARO
FECHA DE VENCIMIENTO: 2023-03-16 00:00:00
-----
Fila 141:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-08-06 00:00:00
-----
Fila 142:
NOMBRE: DISTRIBUIDORA LIVERPOOL
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 143:
NOMBRE: TRATAMIENTOS TERMICOS DE QUERETARO
FECHA DE VENCIMIENTO: 2023-02-01 00:00:00
-----
Fila 144:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-11-09 00:00:00
-----
Fila 145:
NOMBRE: CAPTIVE SPORT
FECHA DE VENCIMIENTO: 2021-09-06 00:00:00
-----
Fila 146:
NOMBRE: HEVACSA TERMOENCOGIBLES
FECHA DE VENCIMIENTO: 2023-03-07 00:00:00
-----
Fila 147:
NOMBRE: ELECTRO FERRETERA REAL
FECHA DE VENCIMIENTO: 2023-03-08 00:00:00
-----
Fila 148:
NOMBRE: SCIMPLA
FECHA DE VENCIMIENTO: 2022-05-10 00:00:00
-----
Fila 149:
NOMBRE: ANA KARLA ROSALES VAZQUEZ
FECHA DE VENCIMIENTO: 2023-02-07 00:00:00
-----
Fila 150:
NOMBRE: LBQ FOUNDRY
FECHA DE VENCIMIENTO: 2023-03-18 00:00:00
-----
Fila 151:
NOMBRE: MANUFACTURERA SLY
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 152:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-08-26 00:00:00
-----
Fila 153:
NOMBRE: J H MILLS
FECHA DE VENCIMIENTO: 2023-03-07 00:00:00
-----
Fila 154:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-08-31 00:00:00
-----
Fila 155:
NOMBRE: BURBUPAC DE QUERETARO
FECHA DE VENCIMIENTO: 2023-04-07 00:00:00
-----
Fila 156:
NOMBRE: AT Y V DESARROLLOS Y MANUFACTURAS
FECHA DE VENCIMIENTO: 2023-03-15 00:00:00
-----
Fila 157:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 158:
NOMBRE: OLMO RACKS & DUNNAGE
FECHA DE VENCIMIENTO: 2022-06-28 00:00:00
-----
Fila 159:
NOMBRE: CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL
FECHA DE VENCIMIENTO: 2023-01-31 00:00:00
-----
Fila 160:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2023-03-07 00:00:00
-----
Fila 161:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2023-03-09 00:00:00
-----
Fila 162:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2023-03-09 00:00:00
-----
Fila 163:
NOMBRE: FISHERS QUERETARO
FECHA DE VENCIMIENTO: 2022-05-27 00:00:00
-----

**OPERACIONES FUNDAMENTALES**

In [ ]:
#Convertir cada nombre a mayúsculas
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.upper())

In [ ]:
#Convertir cada nombre a minúsculas
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.lower())

In [ ]:
#Convertir la primera letra del registro en mayúscula
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.capitalize())

In [ ]:
#Convertir la primera letra de cada palabra en mayúscula
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.title())

In [ ]:
#Contar cuántas letras tiene cada nombre
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre, "tiene", len(nombre), "letras")

In [ ]:
#Mostrar solamente los nombres que tienen menos de 15 letras
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    
    if len(nombre) < 15:
        print(nombre)

In [38]:
#Crear un saludo para cada nombre
def saludar(nombre):
    return "Hola " + nombre + ", bienvenid@!"

for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(saludar(nombre))

Hola DONGA HWASUNG MEXICO, bienvenid@!
Hola DONGA HWASUNG MEXICO, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola INDUSTRIAS LANCERMEX, bienvenid@!
Hola HELVEX, bienvenid@!
Hola AUTOLIV STEERING WHEELS MEXICO, bienvenid@!
Hola AUTOLIV STEERING WHEELS MEXICO, bienvenid@!
Hola BUSSMANN, bienvenid@!
Hola CLAVOS NACIONALES C.N, bienvenid@!
Hola CLAVOS NACIONALES C.N, bienvenid@!
Hola RICHALUM, bienvenid@!
Hola TRANSPORTADORES Y FABRICACIONES INDUSTRIALES, bienvenid@!
Hola INDUSTRIAS LANCERMEX, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola AUTOLIV STEERING WHEELS MEXICO, bienvenid@!
Hola PQUISEM, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola MOLINERA DE MEXICO, bienvenid@!
Hola Q SEALS DE MEXICO, bienvenid@!
Hola Q SEALS DE MEXICO, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola DEACERO, bienvenid@!
Hola TE.MEX AUTOMOTIVE, bienvenid@!
Hola DIECASTING CELAYA, bienvenid@!
Hola CLAVOS NACIONALES C.N, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola PLENCO DE MEXICO, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola DEACERO, bienvenid@!
Hola GLASSER, bienvenid@!
Hola NESTLE MEXICO, bienvenid@!
Hola AIRBUS HELICOPTERS MEXICO QUERETARO, bienvenid@!
Hola AIRBUS HELICOPTERS MEXICO QUERETARO, bienvenid@!
Hola SIKA MEXICANA, bienvenid@!
Hola COVEMEX, bienvenid@!
Hola HOT MELT SISTEMAS Y SERVICIOS SANCHEZ, bienvenid@!
Hola EDGAR GARCIA HERNANDEZ, bienvenid@!
Hola BUSSMANN, bienvenid@!
Hola SIKA MEXICANA, bienvenid@!
Hola DWK LIFE SCIENCES, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola DONGA HWASUNG MEXICO, bienvenid@!
Hola BACHOCO, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola PREFORMADOS DE MEXICO, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola EMPACADORA CELAYA, bienvenid@!
Hola FIDEICOMISO F/1596, bienvenid@!
Hola DWK LIFE SCIENCES, bienvenid@!
Hola DONGA HWASUNG MEXICO, bienvenid@!
Hola DEACERO, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola TRANSPORTADORES Y FABRICACIONES INDUSTRIALES, bienvenid@!
Hola BETA PROCESOS, bienvenid@!
Hola DEACERO, bienvenid@!
Hola BEDACOM, bienvenid@!
Hola NIHON PLAST MEXICANA, bienvenid@!
Hola GLASSER, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola FRESCOS DON GU, bienvenid@!
Hola DEACERO, bienvenid@!
Hola KERN LIEBERS MEXICO, bienvenid@!
Hola PQUISEM, bienvenid@!
Hola EDGAR GARCIA HERNANDEZ, bienvenid@!
Hola KERN LIEBERS MEXICO, bienvenid@!
Hola DEACERO, bienvenid@!
Hola CONTROLADORA MABE, bienvenid@!
Hola ITW POLY MEX, bienvenid@!
Hola ANA BARBARA CRUZ PALACIOS, bienvenid@!
Hola ARMANDO VIDAURRETA PEÑA, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola DISTRIBUCIONES Y REPRESENTACIONES CALORA, bienvenid@!
Hola OERLIKON BALZERS COATING MEXICO, bienvenid@!
Hola APEX TOOL GROUP MANUFACTURING MEXICO, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola TRANSPORTADORES Y FABRICACIONES INDUSTRIALES, bienvenid@!
Hola HOBBY ELECTRONICA, bienvenid@!
Hola DAVID LICEA PANDURO, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola INDUSTRIAS TOLJY, bienvenid@!
Hola SANKO GOSEI MEXICO, bienvenid@!
Hola VINILOS, bienvenid@!
Hola CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS INDUSTRIALES, bienvenid@!
Hola EDGAR GARCIA HERNANDEZ, bienvenid@!
Hola KERN LIEBERS MEXICO, bienvenid@!
Hola RL ELECTRICO, bienvenid@!
Hola BETA PROCESOS, bienvenid@!
Hola ITW POLY MEX, bienvenid@!
Hola PERFORMANCE COATING, bienvenid@!
Hola ADVANEX DE MEXICO, bienvenid@!
Hola J. FRANCISCO FERRUZCA HERNANDEZ, bienvenid@!
Hola DEACERO, bienvenid@!
Hola MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACCION DEL CENTRO, bienvenid@!
Hola PRODUCTOS PENNSYLVANIA, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola MEXICANA DE INGENIERIA Y MAQUINARIA, bienvenid@!
Hola APEX TOOL GROUP MANUFACTURING MEXICO, bienvenid@!
Hola PRODUCTOS PENNSYLVANIA, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola RAUL SERVIN AGUILLON, bienvenid@!
Hola BLANCA ROCIO GARCIA MORALES, bienvenid@!
Hola VINILOS, bienvenid@!
Hola ALIMENTOS GOURMET DEL BAJIO, bienvenid@!
Hola DEACERO, bienvenid@!
Hola JORGE HERBERT PEREZ, bienvenid@!
Hola CAPTIVE SPORT, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola ELASTOMEROS DE QUERETARO, bienvenid@!
Hola ABASTECEDORA GOURMET, bienvenid@!
Hola LBQ FOUNDRY, bienvenid@!
Hola FRESCOPACK, bienvenid@!
Hola MARI CARMEN ALONZO MORA, bienvenid@!
Hola HOSPITAL SAN JOSE DE CELAYA, bienvenid@!
Hola SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUSTRIAL, bienvenid@!
Hola CARLOS ALBERTO HERNANDEZ MIRANDA, bienvenid@!
Hola DEX STAR, bienvenid@!
Hola VINILOS, bienvenid@!
Hola EMZ HANAUER DE MEXICO, bienvenid@!
Hola OSANIA CLEANING & SANITIZING, bienvenid@!
Hola KERN LIEBERS MEXICO, bienvenid@!
Hola MECAPRIM SERVICIOS INDUSTRIALES, bienvenid@!
Hola JAKBA-SEE, bienvenid@!
Hola MULTI EQUIPOS AUTOMOTRICES VIZU, bienvenid@!
Hola GRUPO ROCE INDUSTRIAL Y COMERCIAL, bienvenid@!
Hola JOSE ALEJANDRO DIAZ NIETO, bienvenid@!
Hola GRUPO ROCE INDUSTRIAL Y COMERCIAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola TERMOFORMADOS, bienvenid@!
Hola MARATHON SYSTEMS CONTROL, bienvenid@!
Hola FRANCISCO JAVIER MEDINA SANCHEZ, bienvenid@!
Hola GABRIELA GARCIA SANCHEZ, bienvenid@!
Hola MECAPRIM SERVICIOS INDUSTRIALES, bienvenid@!
Hola JOSE ALEJANDRO DIAZ NIETO, bienvenid@!
Hola JV AGRO, bienvenid@!
Hola UCH COMERCIAL, bienvenid@!
Hola POLIETILENOS Y PRODUCTOS DE QUERETARO, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola DISTRIBUIDORA LIVERPOOL, bienvenid@!
Hola TRATAMIENTOS TERMICOS DE QUERETARO, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola CAPTIVE SPORT, bienvenid@!
Hola HEVACSA TERMOENCOGIBLES, bienvenid@!
Hola ELECTRO FERRETERA REAL, bienvenid@!
Hola SCIMPLA, bienvenid@!
Hola ANA KARLA ROSALES VAZQUEZ, bienvenid@!
Hola LBQ FOUNDRY, bienvenid@!
Hola MANUFACTURERA SLY, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola J H MILLS, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola BURBUPAC DE QUERETARO, bienvenid@!
Hola AT Y V DESARROLLOS Y MANUFACTURAS, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola OLMO RACKS & DUNNAGE, bienvenid@!
Hola CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola FISHERS QUERETARO, bienvenid@!

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [14]:
#Filtro por objeto
filtro1=df[df["NOMBRE"] == "INDUSTRIAS LANCERMEX"]
filtro1

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
12,3930,INDUSTRIAS LANCERMEX,F40114,2023-02-09,2023-03-11,35143.82

In [15]:
#Filtro por filas
#filtro2= df.iloc[3:11,: ]           #Filas consecutivas
#filtro2=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas
filtro2= df.iloc[ [0] + list(range(10, 14)) + [50] , : ]  #Filas combinadas
filtro2

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
10,3937,RICHALUM,F40361,2023-03-14,2023-03-14,42880.05
11,2046,TRANSPORTADORES Y FABRICACIONES INDUSTRIALES,F40118,2023-02-10,2023-03-12,37588.59
12,3930,INDUSTRIAS LANCERMEX,F40114,2023-02-09,2023-03-11,35143.82
13,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40171,2023-02-17,2023-03-19,34493.76
50,6396,DWK LIFE SCIENCES,F40209,2023-02-22,2023-03-24,9472.53

In [16]:
#Filtro por columnas
#filtro3=df.iloc[ : , 0:3]       #Columnas consecutivas
#filtro3=df.iloc[ : , [1,4,6]]  #Columnas no consecutivas
filtro3= df.iloc[ :, [0] + list(range(1, 4)) + [5] ]  #Filas combinadas
filtro3

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,52715.74
4,4712,HELVEX,F40173,2023-02-17,50639.80
...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,19.94

In [ ]:
#GOOGLE COLAB
#Filtro de filas vs columnas
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()

In [17]:
df1= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx', index_col=1)
df1

,No. CLIENTE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
NOMBRE,,,,,
DONGA HWASUNG MEXICO,6401,F40238,2023-02-24,2023-03-26,97485.94
DONGA HWASUNG MEXICO,6401,F40353,2023-03-14,2023-04-13,97485.94
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,4598,F40352,2023-03-14,2023-04-13,64916.21
INDUSTRIAS LANCERMEX,3930,F40217,2023-02-23,2023-03-25,52715.74
HELVEX,4712,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL,856,F40055,2023-01-31,2023-01-31,56.00
PÚBLICO EN GENERAL,5926,NV00777,2023-03-07,2023-03-07,45.00
PÚBLICO EN GENERAL,5926,NV00778,2023-03-09,2023-03-09,40.00
PÚBLICO EN GENERAL,5926,NV00779,2023-03-09,2023-03-09,24.01
FISHERS QUERETARO,8429,F38248,2022-05-27,2022-05-27,19.94

In [18]:
#Paso 2: Aplicamos Filtro de filas vs columnas
filtro4=df1.loc[["HELVEX","DONGA HWASUNG MEXICO"], ["MONTO ADEUDADO"]]
filtro4

                      MONTO ADEUDADO
NOMBRE
HELVEX                      50639.80
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        10759.00
DONGA HWASUNG MEXICO         9396.00

In [19]:
#Filtro por cabecera
filtro5=df.head()
filtro5

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [20]:
#Filtro por comparacion
filtro6=df[df["MONTO ADEUDADO"] == 1000]
filtro6

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
128,2704,GRUPO ROCE INDUSTRIAL Y COMERCIAL,F40077,2023-02-02,2023-02-02,1000.0
129,5926,PÚBLICO EN GENERAL,F36340,2021-10-05,2021-10-05,1000.0
130,5926,PÚBLICO EN GENERAL,F37204,2022-01-27,2022-01-27,1000.0

**FILTROS BASICOS CON CONETORES LOGICOS**

In [21]:
#Filtro Y
filtro7=df[(df["MONTO ADEUDADO"] < 6000) & (df["FECHA_FACTURA"] == "2023-03-14")]
filtro7

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
85,409,CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS IN...,F40359,2023-03-14,2023-03-14,4292.00
96,3926,PRODUCTOS PENNSYLVANIA,F40358,2023-03-14,2023-04-13,3368.64
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16
101,5926,PÚBLICO EN GENERAL,F40362,2023-03-14,2023-03-14,2694.95
113,2216,FRESCOPACK,F40355,2023-03-14,2023-03-14,1682.00
132,1284,TERMOFORMADOS,F40349,2023-03-14,2023-04-13,799.24
135,8872,GABRIELA GARCIA SANCHEZ,F40360,2023-03-14,2023-03-14,754.00
139,8228,UCH COMERCIAL,F40365,2023-03-14,2023-03-14,702.96

In [22]:
#Filtro o
filtro8=df[(df["MONTO ADEUDADO"] < 6000) | (df["FECHA_FACTURA"] == "2023-03-14")]
filtro8

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34
10,3937,RICHALUM,F40361,2023-03-14,2023-03-14,42880.05
36,417,COVEMEX,F40354,2023-03-14,2023-03-29,15843.28
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [23]:
#Filtro not
filtro9=df[~(df["MONTO ADEUDADO"] >= 6000)]
filtro9

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
70,1852,ITW POLY MEX,F40201,2023-02-22,2023-03-24,5967.85
71,8316,ANA BARBARA CRUZ PALACIOS,F40379,2023-03-16,2023-03-31,5827.84
72,8787,ARMANDO VIDAURRETA PEÑA,F39769,2022-12-14,2022-12-14,5800.00
73,2768,CEREALES Y PASTAS,F40215,2023-02-22,2023-03-24,5660.80
74,1831,DISTRIBUCIONES Y REPRESENTACIONES CALORA,F40316,2023-03-08,2023-04-22,5502.81
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [24]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("Entregable1.csv")

In [ ]:
#GOOGLE COLAB
#descardar archivo filtrado en csv
from google.colab import files


files.download("Entregable1.csv")